### PR TITLE
Allow creating a Downloader from a pre-configured reqwest::Client

### LINKED ISSUE #17: Support building a Downloader using a provided (and pre-configured) reqwest::Client
A user might want to use reqwest::Client features which this library doesn't have support for configuring, one easy and generic way around that would be to allow building a downloader with a provided request::Client dependency.

e.g.

* proxy configuration
* tls client cert configuration
* custom CA bundles

It might also make sense to support those features directly and I can file separate issues for those if you agree.

### PR DESCRIPTION
**Pull request by dralley**
closes #17

### CODE REVIEW

**Review by hunger — APPROVED** [review]
Looks sensible:-)

**Comment by hunger** [comment]
Sorry, I turned up clippy to 11 :-) Can you fix the warnings it has?

Otherwise I will do that as soon as I can find the time and afterwards.

What are your plans? Do you have more changes in the pipeline?

We should get this out to users and have a release once you are done :-)

**Comment by dralley** [comment]
>What are your plans? Do you have more changes in the pipeline?

I don't have a lot of plans, just a couple of ideas and I haven't necessarily decided to what degree they make sense yet.  When I decide that I don't need or have time to submit PRs for the immediate future I can let you know

**Comment by hunger** [comment]
Take your time, I'll try to do a release over the weekend (if I can make that!), so that these improvements get out to users soon.

**Comment by dralley** [comment]
@hunger I'll put these ideas forward for your consideration - whether they actually make sense for most users or align with your vision I leave up to you :)  I'm only familiar with my own particular use case.

1) If you're doing mirrored downloads, usually you will start from a set of mirror URLS and some number of relative paths within the mirror which are the same across all of the mirrors.  e.g.

* ftp.au.debian.org/debian/
* ftp.ca.debian.org/debian/
* ftp.cz.debian.org/debian/
* ftp.us.debian.org/debian/

With the current API you have to manually join the base mirror URLs together with the paths you want to download and pass those in as your mirrors.  It would be nice if there was an API which would do all of that for you.

2) The current approach to mirroring is that a URL is picked at random from the list and attempted until one works or the retry limit is reached.  But you might want to configure that so that the list is traversed in order and one mirror is preferred.

Or: if you're downloading a bunch of files from the same set of mirrors, maybe you want to start ranking the mirrors over time based on download speed and encountered errors (so that you don't keep hitting mirrors that are slow, or outdated).

I haven't worked out an API for that yet but maybe it could look like this (I haven't tried it yet so it would probably need tweaking to work)

```Rust
enum MirrorStrategy {
    Order,
    Random,
    Smart,
}

struct MirrorContext {
    strategy: MirrorStrategy,
    urls: Vec<String>,
    // store extra data or some data structure which would help rank them
    // probably use RefCell or something so it can be mutated
}

impl MirrorContext {
    fn mirror_iter(&self) -> Box<dyn Iterator<Item=String>> {
         match self.strategy {
              MirrorStrategy::Order => Box::new(self.urls.iter()),
              // figure out how to implement the others
         }
    }
}

let debian_mirrors = MirrorContext::new(vec![ "http://blahblahblah.com/debian/", "http://foobarbaz.com/debian/" ]).strategy(MirrorStrategy::Smart);

let dl = Download::new_mirrored(debian_mirrors, "README.txt");
```


The trouble is that if you 

3) Both of the bits of data above conceptually feel more like context for the download rather than part of the download-er, if that makes any sense.  The client details, concurrency and retry-ability are details about "how" the downloads ought to be performed whereas the download folder is a "where" and the

**Comment by hunger** [comment]
The use case I originally had in mind was package download from a set of mirrors. That would probably benefit from this.

Just keep in mind that this is supposed to be simple, so watch out for the big picture and hide away as much complexity as possible:-)

**Comment by hunger** [comment]
Not that I think thks API is hard to use or anythkng:-) Actually I like the mirror setup a lot.

**Comment by dralley** [comment]
Right, it might not fit with the overall vision.  I guess I can just start with the mirror context stuff since it's fairly trivial.

**Comment by hunger** [comment]
The feature is fine! Do not let me discourage you from implementing it!

I would just like to make sure there is a easy and obvious path to just grab some URLs.

**Pull request merged**
