### PR TITLE
Add a simple TUI example

### PR DESCRIPTION
**Pull request by phnixir**
The only example that existed was very thorough but for basic usage of the library it had too much code, so i modified it a bit and came up with this! This will definitely make getting started with the library easier.

### CODE REVIEW

**Review by hunger — COMMENTED** [review]
Wow, thank you! I had not expected anybody would ever send in a PR for this little library!

Do you want to adapt the copyright header though? It is your patch! I can also adjust this if that is OK with you.

**Comment by hunger** [comment]
Changing the copyright would also be a wonderful opportunity to make clippy happy:-)

**Comment by phnixir** [comment]
Of course, this library was the best one i could find so naturally i would be happy to contribute.
And it'd also be great if you could adjust it since I'm currently not on my pc, thank you!

**Comment by hunger** [comment]
I fixed the clippy hints in the meantime, those should go away now after rebasing your patches.

Thanks again for your contribution!

**Pull request merged**
